[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/api/dashboard"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "8000"
FLASK_ENV = "production" 