[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/dashboard"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
FLASK_ENV = "production" 