"""
Stock Universe Configuration
Define custom stock lists for market scanning.
"""

# NIFTY 500 - Comprehensive list of major NSE stocks
NIFTY_500_UNIVERSE = [
    # NIFTY 50 (Top 50 stocks by market cap)
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "ITC", "SBIN",
    "BHARTIARTL", "AXISBANK", "ASIANPAINT", "MARUTI", "HCLTECH", "ULTRACEMCO",
    "SUNPHARMA", "TITAN", "WIPRO", "BAJFINANCE", "NESTLEIND", "POWERGRID",
    "KOTAKBANK", "LT", "ADANIENT", "ADANIPORTS", "COALINDIA", "DIVISLAB",
    "DRREDDY", "EICHERMOT", "GAIL", "HEROMOTOCO", "HINDALCO", "JSWSTEEL",
    "BPCL", "M&M", "NTPC", "ONGC", "SHREECEM", "TATAMOTORS", "TATASTEEL",
    "TECHM", "UPL", "VEDL", "GRASIM", "CIPLA", "BAJAJFINSV", "BAJAJ-AUTO",
    "BRITANNIA", "INDUSINDBK", "TATACONSUM", "APOLLOHOSP",
    
    # NIFTY NEXT 50 (Next 50 largest stocks)
    "GODREJCP", "PIDILITIND", "DABUR", "MARICO", "COLPAL", "BERGEPAINT", "PAGEIND",
    "INDIGO", "MCDOWELL-N", "MOTHERSUMI", "MUTHOOTFIN", "BIOCON", "BOSCHLTD",
    "AMBUJACEM", "ACC", "SIEMENS", "HAVELLS", "VOLTAS", "JINDALSTEL", "TRENT",
    "BANDHANBNK", "TORNTPHARM", "CADILAHC", "LUPIN", "GLENMARK", "SRTRANSFIN",
    "AUROPHARMA", "CONCOR", "SAIL", "NMDC", "RECLTD", "PFC", "IRCTC", "HAL",
    "BEL", "BHEL", "IOC", "HPCL", "RAILTEL", "IRFC", "IREDA", "SJVN", "NHPC",
    "THERMAX", "NBCC", "FEDERALBNK", "YESBANK", "IDFCFIRSTB", "RBLBANK",
    
    # Banking and Financial Services (Additional)
    "EQUITASBNK", "AUBANK", "CHOLAFIN", "BAJAJHLDNG", "LICHSGFIN", "MANAPPURAM",
    "L&TFH", "SHRIRAMFIN", "CANBK", "UNIONBANK", "BANKBARODA", "PNB",
    "INDIANB", "CENTRALBK", "IBREALEST", "CESC", "POWERGRID",
    
    # Auto and Auto Ancillaries
    "ASHOKLEY", "ESCORTS", "MAHINDRA", "TVSMOTOR", "APOLLOTYRE", "MRF",
    "BALKRISIND", "ENDURANCE", "RAMCOCEM", "EXIDEIND", "MOTHERSUMI",
    "SUNDRMFAST", "BHARATFORG", "MINDAIND", "SPARC", "TUBE",
    
    # Information Technology
    "MINDTREE", "LTTS", "COFORGE", "PERSISTENT", "MPHASIS", "LTIM",
    "CYIENT", "ZENTEC", "SONACOMS", "KPITTECH", "RAMCOIND", "RPOWER",
    "HFCL", "RAILTEL", "LTTS", "INFRATEL", "BHARTIARTL",
    
    # Pharmaceuticals and Healthcare
    "REDDY", "GLAND", "GRANULES", "DIVIS", "LALPATHLAB", "METROPOLIS",
    "THYROCARE", "SYNGENE", "NATCOPHARM", "JUBLFOOD", "IPCALAB",
    "STRIDES", "ALKEM", "ABBOTINDIA", "ASTRAZEN", "GLAXO", "PFIZER",
    "NOVARTIS", "SANOFI", "TORNTPHARM", "FORTIS", "MAXHEALTH",
    
    # Consumer Goods and Retail
    "AVENUE", "RELAXO", "VBL", "HONAUT", "PGHH", "EMAMILTD", "VGUARD",
    "CROMPTON", "WHIRLPOOL", "DIXON", "AMBER", "SHOPERSTOP", "JUBLFOOD",
    "GODREJIND", "GODREJCP", "BATAINDIA", "RADICO", "MCDOWELL",
    "VENKEYS", "KRBL", "USHAMART", "SYMPHONY", "BLUEDART",
    
    # Metals and Mining
    "JSW", "NATIONALUM", "MOIL", "RATNAMANI", "APL", "WELCORP", "GMRINFRA",
    "ADANIGREEN", "ADANITRANS", "ADANIPOWER", "JINDALSTEL", "JSPL",
    "HINDZINC", "VEDL", "NALCO", "SAIL", "NMDC", "COALINDIA",
    
    # Chemicals and Petrochemicals
    "KANSAINER", "DEEPAKNTR", "ALKYLAMINE", "CLEAN", "NOCIL", "TATACHEM",
    "BALRAMCHIN", "GUJALKALI", "CHAMBLFERT", "GSFC", "NFL", "RCF",
    "GNFC", "FACT", "MADRASFERT", "ZUARI", "COROMANDEL", "PIIND",
    
    # Infrastructure and Construction
    "IRCON", "RITES", "IRFC", "PFC", "RECLTD", "HUDCO", "NBCC",
    "NCC", "HCC", "JAIPRAKASH", "JPASSOCIAT", "PUNJABTRAD",
    "ORIENTCEM", "JKCEMENT", "HEIDELBERG", "PRISMCEM",
    
    # Telecom and Media
    "BHARTIARTL", "VODAIDEA", "TATACOMM", "HFCL", "RAILTEL",
    "GTLINFRA", "RCOM", "TTML", "ZEEL", "SUNTV", "TVTODAY",
    "DISHTV", "NETWORK18", "TV18BRDCST", "JAGRAN", "DBCORP"
]

# Sector-specific universes for focused scanning

BANKING_UNIVERSE = [
    "HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "INDUSINDBK",
    "FEDERALBNK", "YESBANK", "IDFCFIRSTB", "RBLBANK", "EQUITASBNK", "AUBANK",
    "CANBK", "UNIONBANK", "BANKBARODA", "PNB", "INDIANB", "CENTRALBK"
]

IT_UNIVERSE = [
    "TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "MINDTREE", "LTTS",
    "COFORGE", "PERSISTENT", "MPHASIS", "LTIM", "CYIENT", "ZENTEC",
    "SONACOMS", "KPITTECH", "RAMCOIND"
]

PHARMA_UNIVERSE = [
    "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "LUPIN", "AUROPHARMA",
    "CADILAHC", "TORNTPHARM", "BIOCON", "GLAND", "GRANULES", "DIVIS",
    "LALPATHLAB", "METROPOLIS", "THYROCARE", "SYNGENE", "NATCOPHARM"
]

AUTO_UNIVERSE = [
    "MARUTI", "M&M", "TATAMOTORS", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO",
    "TVSMOTOR", "ASHOKLEY", "ESCORTS", "MAHINDRA", "APOLLOTYRE", "MRF",
    "BALKRISIND", "ENDURANCE", "MOTHERSUMI"
]

# Quick setup configurations
CONSERVATIVE_UNIVERSE = [
    # Only NIFTY 50 stocks for stable, high-liquidity scanning
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "ITC", "SBIN",
    "BHARTIARTL", "AXISBANK", "ASIANPAINT", "MARUTI", "HCLTECH", "ULTRACEMCO",
    "SUNPHARMA", "TITAN", "WIPRO", "BAJFINANCE", "NESTLEIND", "POWERGRID",
    "KOTAKBANK", "LT", "ADANIENT", "ADANIPORTS", "COALINDIA", "DIVISLAB",
    "DRREDDY", "EICHERMOT", "GAIL", "HEROMOTOCO", "HINDALCO", "JSWSTEEL",
    "BPCL", "M&M", "NTPC", "ONGC", "SHREECEM", "TATAMOTORS", "TATASTEEL",
    "TECHM", "UPL", "VEDL", "GRASIM", "CIPLA", "BAJAJFINSV", "BAJAJ-AUTO",
    "BRITANNIA", "INDUSINDBK", "TATACONSUM", "APOLLOHOSP"
]

AGGRESSIVE_UNIVERSE = NIFTY_500_UNIVERSE  # Use the full NIFTY 500 for maximum coverage

# Example configuration for different trading styles
INTRADAY_UNIVERSE = [
    # High-volume, liquid stocks ideal for intraday trading
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "SBIN", "BHARTIARTL",
    "AXISBANK", "ITC", "MARUTI", "BAJFINANCE", "TATAMOTORS", "VEDL", "ONGC",
    "COALINDIA", "NTPC", "POWERGRID", "SAIL", "JINDALSTEL", "JSWSTEEL"
]

SWING_UNIVERSE = CONSERVATIVE_UNIVERSE  # NIFTY 50 for swing trading

POSITIONAL_UNIVERSE = NIFTY_500_UNIVERSE  # Full universe for positional trades 